import { TOUR_MESSAGES_CONV_ID } from '@/utils/tourMocks';
import type { TourStepDef } from '@/components/features/explore/product-tour/tourTypes';

export const TOUR_STEPS: TourStepDef[] = [
  {
    route: '/factory-ideas',
    mockScenario: 'browse',
    targetSelector: '[data-tour="tab-product"]',
    targetTexts: ['สินค้า', 'ทั้งหมด'],
    spotlightRadius: 24,
    spotlightPad: 6,
    badgeColor: 'var(--brand-purple)',
    icon: '🔍',
    badge: 'ขั้นตอนที่ 1 / 7',
    title: 'เลือกดูสินค้าและโรงงาน',
    desc: 'เลือกดูสินค้าตัวอย่าง วัตถุดิบ และโรงงานที่สนใจ กรองตามหมวดหมู่ tab ด้านบน หรือค้นหาโดยตรงได้เลย',
    tip: '💡 กด tab "สินค้า" เพื่อดูตัวอย่างที่โรงงานเคยผลิต',
  },
  {
    route: '/',
    targetSelector: '[data-tour="create-rfq-cta"], [data-tour="fab"]',
    targetTexts: ['สร้างคำขอราคา'],
    spotlightRadius: 12,
    spotlightPad: 8,
    cardPlacement: 'top',
    badgeColor: 'var(--brand-orange)',
    icon: '➕',
    badge: 'ขั้นตอนที่ 2 / 7',
    title: 'กดปุ่มสร้างคำขอราคา',
    desc: 'เมื่อต้องการเริ่มต้น กดปุ่ม "สร้างคำขอราคา" ที่ sidebar (Desktop) หรือ ปุ่มลอย "+" มุมขวาล่าง (Mobile) เพื่อเข้าสู่ฟอร์มสร้าง คำขอราคา',
    tip: '➕ ปุ่มนี้จะอยู่กับคุณตลอดทุกหน้า กดได้เมื่อพร้อม',
  },
  {
    route: '/create-rfq',
    mockScenario: 'createRfq',
    targetSelector: '[data-tour="request-kind"]',
    targetTexts: ['ประเภทคำขอ', 'ขอตัวอย่างสินค้า', 'ขอราคาผลิต'],
    spotlightRadius: 14,
    spotlightPad: 10,
    badgeColor: 'var(--brand-orange)',
    icon: '📋',
    badge: 'ขั้นตอนที่ 3 / 7',
    title: 'เลือกประเภทคำขอที่เหมาะกับคุณ',
    desc: 'นอกจาก "ขอราคาผลิต OEM" แล้ว คุณยังสามารถเลือก "ขอตัวอย่างสินค้า" หรือ "ขอตัวอย่างวัตถุดิบ" เพื่อทดลองคุณภาพก่อนสั่งจริง',
    tip: '📋 แนะนำเริ่มจาก "ขอตัวอย่างสินค้า" ถ้ายังไม่แน่ใจคุณภาพโรงงาน',
  },
  {
    route: '/product-detail?showcase_id=14',
    mockScenario: 'product',
    targetTexts: ['แชทกับโรงงาน', 'แชท'],
    spotlightRadius: 12,
    cardPlacement: 'top',
    badgeColor: 'var(--brand-teal)',
    icon: '💬',
    badge: 'ขั้นตอนที่ 4 / 7',
    title: 'แชทกับโรงงานที่สนใจ',
    desc: 'กดปุ่ม "แชทกับโรงงาน" เพื่อคุยรายละเอียดโดยตรง ปรับแบบ ขอตัวอย่าง หรือต่อรองราคาได้เลย',
    tip: '💬 โรงงานใน Tryly ทุกรายพร้อมตอนกลับลูกค้าทุกท่าน',
  },
  {
    route: `/messages/${TOUR_MESSAGES_CONV_ID}`,
    mockScenario: 'messages',
    targetTexts: ['📎', 'แนบ RFQ', 'RFQ', 'พิมพ์ข้อความ'],
    spotlightRadius: 10,
    cardPlacement: 'top',
    badgeColor: 'var(--status-info)',
    icon: '📩',
    badge: 'ขั้นตอนที่ 5 / 7',
    title: 'ส่ง คำขอราคา ให้โรงงานใน Chat',
    desc: 'แนบคำขอราคาที่สร้างไว้ในห้องแชท เพื่อให้โรงงานส่งใบเสนอราคาอย่างเป็นทางการกลับมา',
    tip: '📩 โรงงานจะส่งใบเสนอราคาผ่าน Chat และในหน้า คำขอราคา & คำสั่งงาน',
  },
  {
    route: '/rfqs/28',
    mockScenario: 'rfq',
    targetSelector: '[data-tour="offer-card"][data-factory-id="9998"]',
    targetTexts: ['แพ็กเกจจิ้งสัตว์เลี้ยง โปร', 'ยอมรับข้อเสนอ'],
    spotlightRadius: 14,
    spotlightPad: 8,
    badgeColor: 'var(--brand-violet)',
    icon: '⚖️',
    badge: 'ขั้นตอนที่ 6 / 7',
    title: 'เปรียบเทียบและยอมรับข้อเสนอ',
    desc: 'ดูรายละเอียดใบเสนอราคาจากหลายโรงงาน เปรียบเทียบราคา เงื่อนไข และยอมรับข้อเสนอได้',
    tip: '⚖️ ระบบจะแนะนำโรงงานที่คุ้มค่าที่สุดสำหรับงานของคุณ',
  },
  {
    route: '/orders/17',
    mockScenario: 'order',
    targetSelector: '[data-tour="order-tabs"]',
    targetTexts: ['การผลิต', 'ภาพรวม'],
    spotlightRadius: 12,
    spotlightPad: 6,
    cardPlacement: 'bottom',
    badgeColor: 'var(--status-success-bright)',
    icon: '✅',
    badge: 'ขั้นตอนที่ 7 / 7',
    title: 'จ่ายเงินและติดตามสถานะ',
    desc: 'ชำระเงินผ่านระบบ Tryly แล้วติดตามสถานะการผลิตจนถึงมือคุณ',
    tip: '🔒 เงินจะโอนให้โรงงานเมื่อคุณรับสินค้าแล้วเท่านั้น',
  },
];
